[theme]
base = "dark"
primaryColor = "#FF6B35"
backgroundColor = "#1a1a2e"
secondaryBackgroundColor = "#2a2a3e"
textColor = "#E8F4FD"
font = "sans serif"

[server]
headless = true
port = 8501
maxUploadSize = 200

[browser]
gatherUsageStats = false
showErrorDetails = true

[client]
showErrorDetails = true 